apiVersion: v1
kind: Service
metadata:
  name: eng
spec:
  selector:
    app: eng
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
