server:
  jetty:
    threads:
      min: 20
      max: 20
  port: 11111
spring:
  datasource:
    hikari:
      idle-timeout: 10000
      connection-timeout: 1000
      minimum-idle: 2
      maximum-pool-size: 2
      pool-name: ${spring.application.name}
    url: jdbc:postgresql://localhost:5432/${spring.application.name}
    username: postgres
    password: pwd
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          min-idle: 5
          max-idle: 10
          max-active: 10
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 8
      missing-topics-fatal: false
      ack-mode: manual_immediate
    consumer:
      auto-offset-reset: earliest
      group-id: ${spring.application.name}
    producer:
      client-id: ${spring.application.name}
      properties:
        interceptor:
          classes: io.clhost.extension.kafka.KafkaProducerLoggingInterceptor
wiremock:
  server:
    port: 8088
client:
  urban-dictionary:
    url: http://localhost:${wiremock.server.port}
  dictionary:
    direct-url: http://localhost:${wiremock.server.port}
    api-url: http://localhost:${wiremock.server.port}
  yandex-cloud-translate:
    translate-url: http://localhost:${wiremock.server.port}
    tokens-url: http://localhost:${wiremock.server.port}
    folder-id: folder-id
    oauth-token: oauth-token
