server:
  jetty:
    threads:
      min: 20
      max: 20
  port: 11111
spring:
  datasource:
    hikari:
      idle-timeout: 10000
      connection-timeout: 1000
      minimum-idle: 2
      maximum-pool-size: 2
      pool-name: ${spring.application.name}
    url: jdbc:postgresql://localhost:5432/${spring.application.name}
    username: postgres
    password: pwd
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          min-idle: 5
          max-idle: 10
          max-active: 10
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 8
      missing-topics-fatal: false
      ack-mode: manual_immediate
    consumer:
      auto-offset-reset: earliest
      group-id: ${spring.application.name}
    producer:
      client-id: ${spring.application.name}
      properties:
        interceptor:
          classes: io.clhost.extension.kafka.KafkaProducerLoggingInterceptor
client:
  urban-dictionary:
    url: https://api.urbandictionary.com
  dictionary:
    direct-url: https://www.dictionary.com
    api-url: https://api-portal.dictionary.com/dcom
  yandex-cloud:
    translate-url: https://translate.api.cloud.yandex.net/translate/v2/translate
    tokens-url: https://iam.api.cloud.yandex.net/iam/v1/tokens
    folder-id: b1gigl5qq3r2gsne83s2
    oauth-token: y0_AgAAAAAhjwaxAATuwQAAAADrD-hTFbWXhI6KTXOr19pOwD1-84EMkUo
