server:
  jetty:
    threads:
      min: 20
      max: 20
  port: 11111
client:
  urban-dictionary:
    url: https://api.urbandictionary.com
  dictionary:
    direct-url: https://www.dictionary.com
    api-url: https://api-portal.dictionary.com/dcom
