server:
  jetty:
    threads:
      min: 20
      max: 20
  port: 11111
spring:
  datasource:
    hikari:
      idle-timeout: 10000
      connection-timeout: 1000
      minimum-idle: 2
      maximum-pool-size: 2
      pool-name: ${spring.application.name}
    url: jdbc:postgresql://localhost:5432/${spring.application.name}
    username: postgres
    password: pwd
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 8
      missing-topics-fatal: false
      ack-mode: manual_immediate
    consumer:
      auto-offset-reset: earliest
      group-id: ${spring.application.name}
    producer:
      client-id: ${spring.application.name}
      properties:
        interceptor:
          classes: io.clhost.extension.kafka.KafkaProducerLoggingInterceptor
client:
  urban-dictionary:
    url: https://api.urbandictionary.com
  dictionary:
    direct-url: https://www.dictionary.com
    api-url: https://api-portal.dictionary.com/dcom
  yandex-cloud-translate:
    url: https://translate.api.cloud.yandex.net/translate/v2/translate
    folder-id: b1gigl5qq3r2gsne83s2
    iam-token: t1.9euelZqOjsqalInGkZeMk4-WjMvJze3rnpWakImUzs3LnJ6akZiejMrIzpTl8_c3Ml1Y-e8XICk7_d3z93dgWlj57xcgKTv9zef1656VmpqJnpGdzI2JmZ6Oysyaj4-X7_zF656VmpqJnpGdzI2JmZ6Oysyaj4-X.QS2XukN9SUaO7wzn0k9aQoVQjt5FmF0IrQ-xd91fGbuFTY2lLPky_tRk7dHAYiYkyIl22U_h-FdCgdfdm9uOBA
