server:
  jetty:
    threads:
      min: 20
      max: 20
  port: 11111
wiremock:
  server:
    port: 8088
client:
  urban-dictionary:
    url: http://localhost:${wiremock.server.port}
  dictionary:
    direct-url: http://localhost:${wiremock.server.port}
    api-url: http://localhost:${wiremock.server.port}
  yandex-cloud-translate:
    url: http://localhost:${wiremock.server.port}
    folder-id: folder-id
    iam-token: iam-token
