apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/redis
  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: redis

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
    role: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: service
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
        role: service
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          volumeMounts:
            - name: redis
              mountPath: /data
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    role: service
spec:
  selector:
    app: redis
    role: service
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
